// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpayU4qqCq9WgXH16e684aoUTvmiw97FA',
    appId: '1:241702346210:web:e7a236cf646f944293edbb',
    messagingSenderId: '241702346210',
    projectId: 'a2groupsstorage',
    authDomain: 'a2groupsstorage.firebaseapp.com',
    storageBucket: 'a2groupsstorage.appspot.com',
    measurementId: 'G-JKBEFJHJXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPEVAIagKq2AtZd8r8vYQJc3M4d4MHFpw',
    appId: '1:241702346210:android:b1d6ca2534a43b9f93edbb',
    messagingSenderId: '241702346210',
    projectId: 'a2groupsstorage',
    storageBucket: 'a2groupsstorage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIikMLHfsWfxw9NNMhhNkOrTVOJe8Ot-A',
    appId: '1:241702346210:ios:5163faabea3b90f093edbb',
    messagingSenderId: '241702346210',
    projectId: 'a2groupsstorage',
    storageBucket: 'a2groupsstorage.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIikMLHfsWfxw9NNMhhNkOrTVOJe8Ot-A',
    appId: '1:241702346210:ios:5163faabea3b90f093edbb',
    messagingSenderId: '241702346210',
    projectId: 'a2groupsstorage',
    storageBucket: 'a2groupsstorage.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Bn-hd4csee90bZtuy8UN-xLtYYei3fQ',
    appId: '1:241702346210:web:18aa24297444d84393edbb',
    messagingSenderId: '241702346210',
    projectId: 'a2groupsstorage',
    authDomain: 'a2groupsstorage.firebaseapp.com',
    storageBucket: 'a2groupsstorage.appspot.com',
    measurementId: 'G-TN3K38967N',
  );
}
